{{- range $loadbalancer := .Values.loadbalancer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $loadbalancer.name }}
spec:
  ports:
  - port: {{ $loadbalancer.port }}
    targetPort: {{ $loadbalancer.port }}
  selector:
    app: {{ $loadbalancer.selector }}
  type: LoadBalancer
---
{{- end }}